// Add action types for managing companies

export const GET_COMPANY = "GET_COMPANY_START";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";
export const GET_COMPANY_FAILURE = "GET_COMPANY_FAILURE";

export const GET_COMPANIES = "GET_COMPANIES_START";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS";
export const GET_COMPANIES_FAILURE = "GET_COMPANIES_FAILURE";

export const DELETE_COMPANY = "DELETE_COMPANY_START";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_FAILURE = "DELETE_COMPANY_FAILURE";

export const EDIT_COMPANY = "EDIT_COMPANY_START";
export const EDIT_COMPANY_SUCCESS = "EDIT_COMPANY_SUCCESS";
export const EDIT_COMPANY_FAILURE = "EDIT_COMPANY_FAILURE";

export const ADD_EMPLOYEE = "ADD_EMPLOYEE_START";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILURE = "ADD_EMPLOYEE_FAILURE";

export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE_START";
export const REMOVE_EMPLOYEE_SUCCESS = "REMOVE_EMPLOYEE_SUCCESS";
export const REMOVE_EMPLOYEE_FAILURE = "REMOVE_EMPLOYEE_FAILURE";

export const ADD_DEPARTMENT_START = "ADD_DEPARTMENT_START";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_FAILURE = "ADD_DEPARTMENT_FAILURE";

export const REMOVE_DEPARTMENT_START = "REMOVE_DEPARTMENT_START";
export const REMOVE_DEPARTMENT_SUCCESS = "REMOVE_DEPARTMENT_SUCCESS";
export const REMOVE_DEPARTMENT_FAILURE = "REMOVE_DEPARTMENT_FAILURE";

export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";
