export const CREATE_DEPARTMENT_START = "CREATE_DEPARTMENT_START";
export const CREATE_DEPARTMENT_SUCCESS = "CREATE_DEPARTMENT_SUCCESS";
export const CREATE_DEPARTMENT_FAILURE = "CREATE_DEPARTMENT_FAILURE";
export const FETCH_DEPARTMENTS_START = "FETCH_DEPARTMENT_START";
export const FETCH_DEPARTMENTS_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENTS_FAILURE = "FETCH_DEPARTMENT_FAILURE";
export const FETCH_SINGLE_DEPARTMENT_START = "FETCH_SINGLE_DEPARTMENT_START";
export const FETCH_SINGLE_DEPARTMENT_SUCCESS =
  "FETCH_SINGLE_DEPARTMENT_SUCCESS";
export const FETCH_SINGLE_DEPARTMENT_FAILURE =
  "FETCH_SINGLE_DEPARTMENT_FAILURE";
export const DELETE_DEPARTMENT_START = "DELETE_DEPARTMENT_START";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_FAILURE = "DELETE_DEPARTMENT_FAILURE";
export const UPDATE_DEPARTMENT_START = "UPDATE_DEPARTMENT_START";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT_FAILURE = "UPDATE_DEPARTMENT_FAILURE";

export const GET_DEPARTMENT_EMPLOYEES_START = "GET_DEPARTMENT_EMPLOYEES_START";
export const GET_DEPARTMENT_EMPLOYEES_SUCCESS =
  "GET_DEPARTMENT_EMPLOYEES_SUCCESS";
export const GET_DEPARTMENT_EMPLOYEES_FAILURE =
  "GET_DEPARTMENT_EMPLOYEES_FAILURE";
