export const CREATE_SHIFT_START = "CREATE_SHIFT_START";
export const CREATE_SHIFT_SUCCESS = "CREATE_SHIFT_SUCCESS";
export const CREATE_SHIFT_FAILURE = "CREATE_SHIFT_FAILURE";

export const GET_SHIFT_START = "GET_SHIFT_START";
export const GET_SHIFT_SUCCESS = "GET_SHIFT_SUCCESS";
export const GET_SHIFT_FAILURE = "GET_SHIFT_FAILURE";

export const GET_SHIFTS_START = "GET_SHIFTS_START";
export const GET_SHIFTS_SUCCESS = "GET_SHIFTS_SUCCESS";
export const GET_SHIFTS_FAILURE = "GET_SHIFTS_FAILURE";

export const UPDATE_SHIFT_START = "UPDATE_SHIFT_START";
export const UPDATE_SHIFT_SUCCESS = "UPDATE_SHIFT_SUCCESS";
export const UPDATE_SHIFT_FAILURE = "UPDATE_SHIFT_FAILURE";

export const DELETE_SHIFT_START = "DELETE_SHIFT_START";
export const DELETE_SHIFT_SUCCESS = "DELETE_SHIFT_SUCCESS";
export const DELETE_SHIFT_FAILURE = "DELETE_SHIFT_FAILURE";

export const ASSIGN_SHIFT_START = "ASSIGN_SHIFT_START";
export const ASSIGN_SHIFT_SUCCESS = "ASSIGN_SHIFT_SUCCESS";
export const ASSIGN_SHIFT_FAILURE = "ASSIGN_SHIFT_FAILURE";

export const UNASSIGN_SHIFT_START = "UNASSIGN_SHIFT_START";
export const UNASSIGN_SHIFT_SUCCESS = "UNASSIGN_SHIFT_SUCCESS";
export const UNASSIGN_SHIFT_FAILURE = "UNASSIGN_SHIFT_FAILURE";

export const GET_SHIFTS_WITH_EMPLOYEES_START =
  "GET_SHIFTS_WITH_EMPLOYEES_START";
export const GET_SHIFTS_WITH_EMPLOYEES_SUCCESS =
  "GET_SHIFTS_WITH_EMPLOYEES_SUCCESS";
export const GET_SHIFTS_WITH_EMPLOYEES_FAILURE =
  "GET_SHIFTS_WITH_EMPLOYEES_FAILURE";
